<a href="https://colab.research.google.com/github/shreyasat27/pennylane-27524/blob/main/pennylane_codebook(1-10).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Codercise l.1.1*

In [1]:
import numpy as np
# Here are the vector representations of |0> and |1>, for convenience
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])


def normalize_state(alpha, beta):
    """Compute a normalized quantum state given arbitrary amplitudes.

    Args:
        alpha (complex): The amplitude associated with the |0> state.
        beta (complex): The amplitude associated with the |1> state.

    Returns:
        np.array[complex]: A vector (numpy array) with 2 elements that represents
        a normalized quantum state.
    """
    # Compute the normalization factor
    norm = np.sqrt(np.abs(alpha)**2 + np.abs(beta)**2)

    # Create the normalized state vector
    normalized_state = np.array([alpha / norm, beta / norm])

    # CREATE A VECTOR [a', b'] BASED ON alpha AND beta SUCH THAT |a'|^2 + |b'|^2 = 1

    # RETURN A VECTOR
    return normalized_state
    pass


*Codercise l.1.2*

In [2]:
def inner_product(state_1, state_2):
    """Compute the inner product between two states.

    Args:
        state_1 (np.array[complex]): A normalized quantum state vector
        state_2 (np.array[complex]): A second normalized quantum state vector

    Returns:
        complex: The value of the inner product <state_1 | state_2>.
    """


    # COMPUTE AND RETURN THE INNER PRODUCT

    return np.vdot(state_1, state_2)



# Test your results with this code
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])

print(f"<0|0> = {inner_product(ket_0, ket_0)}")
print(f"<0|1> = {inner_product(ket_0, ket_1)}")
print(f"<1|0> = {inner_product(ket_1, ket_0)}")
print(f"<1|1> = {inner_product(ket_1, ket_1)}")

<0|0> = 1
<0|1> = 0
<1|0> = 0
<1|1> = 1


*Codercise l.1.3*

In [3]:
def measure_state(state, num_meas):
    """Simulate a quantum measurement process.

    Args:
        state (array[complex]): A normalized qubit state vector.
        num_meas (int): The number of measurements to take

    Returns:
        array[int]: A set of num_meas samples, 0 or 1, chosen according to the probability
        distribution defined by the input state.
    """

    return np.random.choice(2, num_meas, p=[np.abs(state[0])**2, np.abs(state[1])**2])



In [4]:
state = np.array([0.6, 0.8])
U = np.array(([[1, 1], [1, -1]]) / np.sqrt(2))

In [5]:
measure_state(state,10)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

*Codercise I.1.4*

In [6]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)


def apply_u(state):
    """Apply a quantum operation.

    Args:
        state (np.array[complex]): A normalized quantum state vector.

    Returns:
        np.array[complex]: The output state after applying U.
    """

    return np.dot(U,state)

    # APPLY U TO THE INPUT STATE AND RETURN THE NEW STATE
    pass

*Codercise l.1.5*

In [7]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)


def initialize_state():
    """Prepare a qubit in state |0>.

    Returns:
        np.array[float]: the vector representation of state |0>.
    """



    # PREPARE THE STATE |0>
    return np.array([1,0])
    pass

def apply_u(state):
    """Apply a quantum operation."""
    return np.dot(U, state)


def measure_state(state, num_meas):
    """Measure a quantum state num_meas times."""
    p_alpha = np.abs(state[0]) ** 2
    p_beta = np.abs(state[1]) ** 2
    meas_outcome = np.random.choice([0, 1], p=[p_alpha, p_beta], size=num_meas)
    return meas_outcome


def quantum_algorithm():
    """Use the functions above to implement the quantum algorithm described above.

    Try and do so using three lines of code or less!

    Returns:
        np.array[int]: the measurement results after running the algorithm 100 times
    """
    # PREPARE THE STATE, APPLY U, THEN TAKE 100 MEASUREMENT SAMPLES

    state = np.array([1, 0])
    final_state = apply_u(state)
    meas_outcome = measure_state(final_state, 100)
    return meas_outcome
    pass

In [8]:
quantum_algorithm()


array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0])

In [9]:
!pip install pennylane

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 7.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 35.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 46.7 MB/s eta 0:00:00


 *Codercise l.2.1*

In [10]:
#quantum circuits in pennylane

import pennylane as qml

def my_quantum_function(params):

    # Single-qubit operations with no input parameters
    qml.Gate1(wires=0)
    qml.Gate2(wires=1)

    # A single-qubit operation with an input parameter
    qml.Gate3(params[0], wires=0)

    # Two-qubit operation with no input parameter on wires 0 and 1
    qml.TwoQubitGate1(wires=[0, 1])

    # Two-qubit operation with an input parameter on wires 0 and 1
    qml.TwoQubitGate2(params[1], wires=[0, 1])

    # Return the result of a measurement
    return qml.Measurement(wires=[0, 1])

In [11]:
#creating a quantum circuit using quantum gates Rz, H and CNOT

#build a quantum fuction 'my_first_circuit' yo

def my_first_circuit(theta):

    qml.Hadamard(wires =0)
    qml.CNOT(wires = [0,1])
    qml.RZ(theta, wires =0)

    return qml.probs(wires = [0,1])

    pass



*Method-1 to execute the circuit*

In [12]:
dev = qml.device('default.qubit', wires= [0,1])
theta = 90
def my_first_circuit(theta):
    qml.Hadamard(wires =0)
    qml.CNOT(wires =[0,1])
    qml.RZ(theta, wires=0)

    return qml.probs(wires = [0,1])

my_first_QNode = qml.QNode(my_first_circuit, dev)



*Method-2 to execute the circuit*

In [13]:
dev = qml.device('default.qubit', wires =[0,1])

@qml.qnode(dev)
def my_first_circuit(theta):

    qml.Hadamard(wires =0)
    qml.CNOT(wires =[0,1])
    qml.RZ(theta, wires=0)

    return qml.probs(wires = [0,1])



*Codercise l.2.2* Building a QNode

In [14]:
#using the qml.QNode function

# This creates a device with three wires on which PennyLane can run computations
dev = qml.device("default.qubit", wires=3)


def my_circuit(theta, phi, omega):

    # IMPLEMENT THE CIRCUIT BY ADDING THE GATES

    qml.RX(theta, wires=0)
    qml.RY(phi, wires=1)
    qml.RZ(omega, wires=2)
    qml.CNOT(wires=[0, 1])
    qml.CNOT(wires=[1, 2])
    qml.CNOT(wires=[2, 0])


    return qml.probs(wires=[0, 1, 2])


# This creates a QNode, binding the function and device
my_qnode = qml.QNode(my_circuit, dev)

# We set up some values for the input parameters
theta, phi, omega = 0.1, 0.2, 0.3

# Now we can execute the QNode by calling it like we would a regular function
my_qnode(theta, phi, omega)

tensor([9.87560268e-01, 0.00000000e+00, 0.00000000e+00, 2.47302134e-03,
        2.48960206e-05, 0.00000000e+00, 0.00000000e+00, 9.94181506e-03], requires_grad=True)

*Codercise l.2.3* The QNode Decorator

In [15]:
dev = qml.device("default.qubit", wires=3)

@qml.qnode(dev)
# DECORATE THE FUNCTION BELOW TO TURN IT INTO A QNODE


def my_circuit(theta, phi, omega):
    qml.RX(theta, wires=0)
    qml.RY(phi, wires=1)
    qml.RZ(omega, wires=2)
    qml.CNOT(wires=[0, 1])
    qml.CNOT(wires=[1, 2])
    qml.CNOT(wires=[2, 0])
    return qml.probs(wires=[0, 1, 2])


theta, phi, omega = 0.1, 0.2, 0.3

##################
# YOUR CODE HERE #
##################

# RUN THE QNODE WITH THE PROVIDED PARAMETERS
my_circuit(theta, phi,omega)

tensor([9.87560268e-01, 0.00000000e+00, 0.00000000e+00, 2.47302134e-03,
        2.48960206e-05, 0.00000000e+00, 0.00000000e+00, 9.94181506e-03], requires_grad=True)

*Codercise l.2.4*

In [16]:
dev = qml.device("default.qubit", wires=3)


@qml.qnode(dev)
def my_circuit(theta, phi, omega):
    qml.RX(theta, wires=0)
    qml.RY(phi, wires=1)
    qml.RZ(omega, wires=2)
    qml.CNOT(wires=[0, 1])
    qml.CNOT(wires=[1, 2])
    qml.CNOT(wires=[2, 0])
    return qml.probs(wires=[0, 1, 2])


##################
# YOUR CODE HERE #
##################

# FILL IN THE CORRECT CIRCUIT DEPTH
depth = 4

*Codercise l.3.1*

In [17]:
dev = qml.device("default.qubit", wires=1)

U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)


@qml.qnode(dev)
def apply_u():

    # USE QubitUnitary TO APPLY U TO THE QUBIT
    qml.QubitUnitary(U, wires=0)

    # Return the state
    return qml.state()


*Coderise l.3.2* Parametrized

In [18]:
dev = qml.device("default.qubit", wires=1)


@qml.qnode(dev)
def apply_u_as_rot(phi, theta, omega):

    ##################
    # YOUR CODE HERE #
    ##################

    # APPLY A ROT GATE USING THE PROVIDED INPUT PARAMETERS
    qml.Rot(phi, theta, omega, wires =0)
    # RETURN THE QUANTUM STATE VECTOR

    return qml.state()

*Codercise l.4.1* Flipping bits

In [19]:
dev = qml.device("default.qubit", wires=1)

U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)


@qml.qnode(dev)
def varied_initial_state(state):
    """Complete the function such that we can apply the operation U to
    either |0> or |1> depending on the input argument flag.

    Args:
        state (int): Either 0 or 1. If 1, prepare the qubit in state |1>,
            otherwise, leave it in state 0.

    Returns:
        np.array[complex]: The state of the qubit after the operations.
    """


    # KEEP THE QUBIT IN |0> OR CHANGE IT TO |1> DEPENDING ON THE state PARAMETER
    if (state ==1):
       qml.PauliX(wires =0)

    # APPLY U TO THE STATE
    qml.QubitUnitary(U, wires=0)
    return qml.state()


*Codercise l.4.2* Uniform Superpostion (Hadamard gate)

In [20]:
dev = qml.device("default.qubit", wires=1)


@qml.qnode(dev)
def apply_hadamard():

    # APPLY THE HADAMARD GATE
    qml.Hadamard(wires =0)

    # RETURN THE STATE

    return qml.state()

*Codercise l.4.3* Combining X and H Gates

In [21]:
dev = qml.device("default.qubit", wires=1)


@qml.qnode(dev)
def apply_hadamard_to_state(state):
    """Complete the function such that we can apply the Hadamard to
    either |0> or |1> depending on the input argument flag.

    Args:
        state (int): Either 0 or 1. If 1, prepare the qubit in state |1>,
            otherwise, leave it in state 0.

    Returns:
        np.array[complex]: The state of the qubit after the operations.
    """


    # KEEP THE QUBIT IN |0> OR CHANGE IT TO |1> DEPENDING ON state
    if (state ==1):
        qml.PauliX(wires =0)

    # APPLY THE HADAMARD
    qml.Hadamard(wires =0)

    # RETURN THE STATE

    return qml.state()


print(apply_hadamard_to_state(0))
print(apply_hadamard_to_state(1))

[0.70710678+0.j 0.70710678+0.j]
[ 0.70710678+0.j -0.70710678+0.j]


*Codercise l.4.4* A QNode with X and H

In [22]:
# CREATE A DEVICE
dev = qml.device('default.qubit', wires =1)
# CREATE A QNODE CALLED apply_hxh THAT APPLIES THE CIRCUIT ABOVE
@qml.qnode(dev)

def apply_hxh(state):

    if (state ==1):
        qml.PauliX(wires=0)


    qml.Hadamard(wires =0)
    qml.PauliX(wires =0)
    qml.Hadamard(wires =0)

    return qml.state()

# Print your results
print(apply_hxh(0))
print(apply_hxh(1))

[1.+0.j 0.+0.j]
[ 0.+0.j -1.+0.j]


*Codercise l.5.1*

In [23]:
dev = qml.device("default.qubit", wires=1)


@qml.qnode(dev)
def apply_z_to_plus():
    """Write a circuit that applies PauliZ to the |+> state and returns
    the state.

    Returns:
        np.array[complex]: The state of the qubit after the operations.
    """

    # CREATE THE |+> STATE
    qml.Hadamard(wires =0)
    # APPLY PAULI Z
    qml.PauliZ(wires=0)

    # RETURN THE STATE
    return qml.state()


print(apply_z_to_plus())

[ 0.70710678+0.j -0.70710678+0.j]


*Codercise l.5.2*

In [24]:
dev = qml.device("default.qubit", wires=1)


@qml.qnode(dev)
def fake_z():
    """Use RZ to produce the same action as Pauli Z on the |+> state.

    Returns:
        np.array[complex]: The state of the qubit after the operations.
    """

    # CREATE THE |+> STATE
    qml.Hadamard(wires =0)

    # APPLY RZ
    qml.RZ(theta, wires = 0)

    # RETURN THE STATE
    return qml.state()

theta = np.pi

*Codercise l.5.3* S, T Gates

In [25]:
dev = qml.device("default.qubit", wires=1)


@qml.qnode(dev)
def many_rotations():
    """Implement the circuit depicted above and return the quantum state.

    Returns:
        np.array[complex]: The state of the qubit after the operations.
    """

    # IMPLEMENT THE CIRCUIT


    qml.Hadamard(wires=0)
    qml.S(wires =0)
    qml.adjoint(qml.T)(wires=0)
    qml.RZ(0.3,wires =0)
    qml.adjoint(qml.S)(wires=0)

    # RETURN THE STATE

    return qml.state()